[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    --browser=chromium
    --headed
    --screenshot=only-on-failure
    --video=retain-on-failure

log_cli = true
log_cli_level = INFO